### ISSUE TITLE
Cannot download vectors

### ISSUE THREAD

**Issue by krzynio** [dcferreira/multilingual-joint-embeddings#1]
Hi,

This link is broken - can you fix this?

http://camoes.lx.it.pt/amartins/projects/data/multilingual_embeddings.tar.gz

Regards,

K.

**Comment by dcferreira** [comment]
Hi,

The link seems to be working for me. When the download finishes I'll try to upload it to a mirror either way.
In the meanwhile, try the link again.

**Comment by krzynio** [comment]
Thank you for your reply. I tried to download it from few sites in Poland and it failed with timeout, but it works from rented server in Germany.

:)

**Comment by dcferreira** [comment]
I mirrored it here: https://drive.google.com/open?id=1lIsST9on-Ol_EmBlP18IzAB6JQIKMd3v
I guess it should have a better download speed :)

**Comment by davebulaval** [comment]
I have the same issue with this [website](http://www.cs.cmu.edu/~afm/projects/multilingual_embeddings.html). I have use the drive but you should repair the website. Tks for the vectors.
